apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: shahmysql-pass
  literals:
  - password=redhat
resources:
  - mysql-deployment.yml
  - wordpress-deployment.yml