apiVersion:  v1
kind:  PersistentVolumeClaim

metadata:
  name:  shaillypvc1
spec:
  storageClassName:  shahsc1
  accessModes:
    -  ReadWriteOnce
  resources:
    requests:
      storage:  1Gi